backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://the-art-of.netlify.com/

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Video", name: "video", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Gallery" 
        name: "galleryImages"
        widget: "list"
        required: false
        fields: 
          - {label: Alt Tag, name: altTag, widget: string, required: false}
          - {label: Image, name: image, widget: image}
  - label: "About"
    name: 'about'
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: false}